# service-b-throttled.yaml
# DEPLOY THIS FIRST to start the demo in a degraded state.
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-b
 labels:
   app: service-b
spec:
 replicas: 1
 selector:
   matchLabels:
     app: service-b
 template:
   metadata:
     labels:
       app: service-b
   spec:
     containers:
     - name: service-b
       image: khasham1/service-b-java:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
       env:
       - name: WORK_ITERATIONS
         value: "200000"
       - name: SPRING_APPLICATION_NAME
         value: "Service B"
       resources:
         limits:
           cpu: "250m"
       readinessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 15
         periodSeconds: 5
         failureThreshold: 5  
       livenessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 90
         periodSeconds: 10
         failureThreshold: 10 
---
apiVersion: v1
kind: Service
metadata:
 name: service-b-svc
spec:
 type: ClusterIP
 selector:
   app: service-b
 ports:
 - protocol: TCP
   port: 8080
   targetPort: 8080
